using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FibonacciSequence
{
    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    class Program
    {
        static void Main(string[] args)
        {
            //initializing list of Fibonacci Sequence Numbers
            List<int> terms = new List<int>();

            //initializing, and adding to list, the first two terms in Fibonacci sequence
            int a = 1;
            terms.Add (a);
            int b = 2;
            terms.Add (b);
            
            //considering only the Fibonacci terms whose values don't exceed four million
            int max = 4000000;

            //generating the rest of the sequence and adding each FSN to the list
            while (b <= max)
            {
                a = a + b;
                if (a <= max)
                { 
                    terms.Add (a); 
                }
                b = b + a;
                if (b <= max)
                {
                    terms.Add (b);
                }
                             
            }

            //printing the list of FSNs
            Console.WriteLine("Here are the numbers of the Fibonacci sequence with values of 4,000,000 or less: ");
            for (int i = 0; i < terms.Count; i++)
            {
                Console.Write("\t" + terms[i]);
            }
 
            //finding and printing the sum of only the even-valued terms in the above-generated list
            int evenValuedSum = 0;
            for (int j = 0; j < terms.Count; j++)
            {
                if (terms[j] % 2 == 0)
                {
                    evenValuedSum = evenValuedSum + terms[j];
                }
            }
            Console.WriteLine("\n");
            Console.WriteLine("The sum of the even-valued above-listed terms is: " + evenValuedSum);

            Console.Read();

        }
    }
}
